import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {parse} from 'csv-parse/sync';
import {VgcPastesProvider} from '../src/meta/providers/vgc-pastes.js';
import {loadRegulationProfile} from '../src/regulation/profile.js';
import {selectFeaturedCohort} from '../src/simulation/experiment.js';
import {buildTeamBelief} from '../src/simulation/beliefs.js';
import {validateEngineTeam} from '../src/simulation/engine.js';
import {sha256} from '../src/util/hash.js';

const directory='.vgc-helper/experiments/m-c';
mkdirSync(directory,{recursive:true});
const csv=readFileSync(`${directory}/featured-teams.csv`,'utf8');
const rows=parse(csv,{relax_column_count:true,skip_empty_lines:true}) as string[][];
const header=rows.findIndex(row=>row[0]==='Team ID');
if(header<0)throw new Error('Featured Teams header missing');
const columns=rows[header]!,rank=columns.indexOf('Rank'),date=columns.indexOf('Date Shared');
const placement=(value:string)=>/^champion$/i.test(value)?1:/^runner[ -]?up$/i.test(value)?2:Number(value.match(/^(\d+)(?:st|nd|rd|th)?$/i)?.[1]??Infinity);
const eligible=rows.slice(header+1).filter(row=>Number.isFinite(placement(row[rank]??''))).sort((a,b)=>placement(a[rank]!)-placement(b[rank]!)||(Date.parse(b[date]!)||0)-(Date.parse(a[date]!)||0)||a[0]!.localeCompare(b[0]!));
const selected=eligible.slice(0,12);
const subset=[...rows.slice(0,header+1),...selected].map(row=>row.map(cell=>'"'+cell.replaceAll('"','""')+'"').join(',')).join('\n');
const fetcher:typeof fetch=async(input,init)=>String(input).includes('docs.google.com')?new Response(subset):fetch(input,init);
const source=await new VgcPastesProvider({fetch:fetcher,concurrency:3}).fetch(loadRegulationProfile());
const teams=source.data.map(team=>({...team,source:{...team.source,sourceVersion:sha256(csv)}}));
const coverage=teams.map(team=>({id:team.id,candidates:buildTeamBelief({regulationId:team.regulationId,preview:team.pokemon.map(p=>p.species),publishedTeams:[team],validateTeam:validateEngineTeam,maxCandidates:32}).candidates.length,errors:validateEngineTeam({pokemon:team.pokemon})}));
const legal=teams.filter(team=>coverage.find(c=>c.id===team.id)!.candidates>0);
const cohort=selectFeaturedCohort(legal,4);
const result={retrievedAt:new Date().toISOString(),csvHash:sha256(csv),selection:cohort.selection,sourceEligibleRows:eligible.length,inspected:coverage,teams:cohort.teams};
writeFileSync(`${directory}/featured-inspected-teams.json`,JSON.stringify(teams,null,2));
writeFileSync(`${directory}/featured-cohort.json`,JSON.stringify(result,null,2));
console.log(JSON.stringify({selected:result.teams.map(t=>({id:t.id,name:t.name,placement:t.placement,roster:t.roster,unknownSpreads:t.pokemon.filter(p=>!Object.keys(p.skillPoints).length).length})),coverage},null,2));
